name = "shb"
version = "1.00"
description = "SHB 2.12"
author = "xxxx"
forumthread = ""
api_version = 6
api_version_dst = 10
priority = -999999
dont_starve_compatible = true
reign_of_giants_compatible = true
shipwrecked_compatible = true
dst_compatible = true
all_clients_require_mod = true
client_only_mod = false
server_only_mod = true
server_filter_tags = {}
icon_atlas = "preview.xml"
icon = "preview.tex"
